export const selectedProjectsContent = {
  id: 'selected-projects',
  headerLabel: 'SELECTED PROJECTS',
  headline: ['My', 'Portfolio.'],
  projects: [
    {
      title: 'Syncible',
      subtitle: 'Education',
      year: '2024',
      overview: 'Syncible a pioneering platform that provides secure and transparent tokenized certificates for across various sectors, including education, business, and non-profit organizations. Syncible ensures the authenticity and integrity of digital certificates, helping to minimize the risk of counterfeiting and enhancing the credibility of certificate-issuing organizations.',
      whatIDo: '',
      whatILearn: '',
      discoverMore: '',
      tags: ['Tokenized Certificates', 'Platform'],
      industry: ['Web3', 'Education'],
      image: '/assets/Mockup_Syncible.png',
      alt: 'Syncible',
    },
    {
      title: 'Basal Wallet',
      subtitle: 'Wallet',
      year: '2024',
      overview: 'Basal is a top-tier electronic wallet, designed to bring users a secure, private, and user-friendly experience with digital currency.',
      whatIDo: '',
      whatILearn: '',
      discoverMore: '',
      tags: ['Digital Currency', 'Security'],
      industry: ['Web3', 'Wallet'],
      image: '/assets/Basal Wallet.webp',
      alt: 'Basal Wallet',
    },
    {
      title: 'AI Law Search',
      subtitle: 'Asset Management',
      year: '2025',
      overview: 'Fortius is a digital financial platform specializing in digital asset custody services. Built with enterprise-grade precision, it addresses fundamental needs in the digital economy. Fortius Custody supports users in managing and safeguarding their digital assets securely and efficiently.',
      whatIDo: '',
      whatILearn: '',
      discoverMore: '',
      tags: ['Digital Asset', 'Custody'],
      industry: ['Web3', 'Asset Management'],
      image: '',
      alt: 'AI Law Search',
    },
    {
      title: 'ChainTracer',
      subtitle: 'Analysis',
      year: '2025',
      overview: 'ChainTracer is a non-profit initiative designed to trace and identify fraudulent activities on the blockchain. The program provides reliable data on global scams by compiling reports from victims and tracing transactions on the blockchain. Its mission is to prevent the misuse of blockchain technology for fraud, particularly within the digital asset space, while equipping users with the knowledge and tools needed to protect their assets in the Web3 ecosystem.',
      whatIDo: '',
      whatILearn: '',
      discoverMore: '',
      tags: ['Blockchain Analysis', 'Security'],
      industry: ['Web3', 'Analysis'],
      image: '',
      alt: 'ChainTracer',
    },
    {
      title: 'Basal Pay',
      subtitle: 'Payment',
      year: '2026',
      overview: 'Basal Pay empowers foreigners traveling, working, or living in Southeast Asia with a revolutionary QR code transfer solution, enabling seamless, instant transactions like locals—without needing a bank account.',
      whatIDo: '',
      whatILearn: '',
      discoverMore: '',
      tags: ['QR Payment', 'Fintech'],
      industry: ['Web3', 'Payment'],
      image: '/assets/basal-pay.png',
      alt: 'Basal Pay',
    }
  ]
};
