export const selectedProjectsContent = {
  id: 'selected-projects',
  headerLabel: 'SELECTED PROJECTS',
  headline: ['My', 'Portfolio.'],
  projects: [
    {
      title: 'Syncible',
      subtitle: 'NFT Platform',
      year: '2024',
      overview: 'Syncible provides a platform to digitize internal certificates for students of learning academies within VBA ecosystems, making them easier to verify, share, and protect against fraud.',
      whatIDo: 'This was my first project leading, working with a two-person development team to build the entire business logic, website, and platform for users to create certificates, smart contracts, deploy certificates to the blockchain, and export diplomas for students.',
      whatILearn: 'Regarding business: Gaining a deeper understanding of project management frameworks and blockchain business processes.\nRegarding tech: Learning how to collaborate and communicate with the development team on technical aspects and software logic knowledge.',
      discoverMore: 'https://syncible.io/en',
      tags: ['Tokenized Certificates', 'Platform'],
      industry: ['Web3', 'Education'],
      image: '/assets/Mockup_Syncible.png',
      alt: 'Syncible',
    },
    {
      title: 'Basal Wallet',
      subtitle: 'Crypto Wallet',
      year: '2024',
      overview: 'Basal Wallet is a smart contract account‑abstraction wallet that removes seed phrases and native‑token gas, making crypto safer and as easy to use as everyday Web2 apps.',
      whatIDo: 'I work as a Business Analyst on this project, translating business needs into clear functional requirements and coordinating across teams to deliver the product.',
      whatILearn: 'If a product does not clearly define its value proposition and competitive edge from the beginning, bigger players can easily enter the market, and the product is unlikely to achieve product–market fit. As a result, the team may “do things the right way but on the wrong problem,” leading to wasted time and resources.',
      discoverMore: 'https://apps.apple.com/vn/app/basal-wallet/id6478577563',
      tags: ['Digital Currency', 'Security'],
      industry: ['Web3', 'Wallet'],
      image: '/assets/BasalWallet_Mockup.png',
      alt: 'Basal Wallet',
    },
    {
      title: 'AI Law Search',
      subtitle: 'Chatbot AI',
      year: '2025',
      overview: 'AI Law Search is an AI‑powered legal assistant that helps users quickly and accurately look up Vietnamese laws and receive legal guidance within the local regulatory framework.',
      whatIDo: 'I support the leadership team in monetizing the business model once the product reaches MVP, and I develop product plans for subsequent phases as the product gains traction.',
      whatILearn: 'Value is ultimately defined by users. The business model must be clearly defined before the product is built to have a solid basis for defining success. Even if a product gains good traction in sign‑ups and daily usage, it is not truly successful unless it addresses a real pain point that users are willing to pay for.',
      discoverMore: 'https://aitracuuluat.vn',
      tags: ['Digital Asset', 'Custody'],
      industry: ['Web3', 'Asset Management'],
      image: '/assets/AILaw_mockup.png',
      alt: 'AI Law Search',
    },
    {
      title: 'Basal DID',
      subtitle: 'Decentralized Identity',
      year: '2025',
      overview: 'Basal DID is a digital identity wallet infrastructure for storing and presenting verified digital credentials such as ID cards, digital driver’s licenses, membership and loyalty cards...',
      whatIDo: 'In this project, I work as the Business Analyst, clarifying customer needs and defining the product logic. I translate these into clear documentation and collaborate closely with the design and development teams to deliver a DID product on a tight schedule.',
      whatILearn: 'I gained a whole new level of understanding of blockchain and how it can support heavy, real‑world business processes. I learned how to translate complicated operational workflows into clear, implementable blockchain logic while still keeping the user experience simple and practical.',
      discoverMore: 'Product for External-Customer, Non-disclose',
      tags: ['Decentralized Identity', 'Security'],
      industry: ['Web3', 'Analysis'],
      image: '/assets/BasalDID_Mockup.png',
      alt: 'Basal DID',
    },
    {
      title: 'Basal Pay',
      subtitle: 'Crypto Payment',
      year: '2026',
      overview: 'Basal Pay empowers foreigners traveling, working, or living in Southeast Asia with a revolutionary QR code transfer solution, enabling seamless, instant transactions like locals—without needing a bank account.',
      whatIDo: 'As an Operations Manager in a startup environment, I oversee end‑to‑end operations to keep workflows running smoothly. I manage and balance the treasury, support product management, shape go‑to‑market strategy, remove operational bottlenecks, and develop strategic partnerships for the product.',
      whatILearn: 'Every decision comes with trade‑offs, and timing is a critical factor in product strategy. I also realized that a “build first, improve later” mindset is essential for staying lean, instead of waiting for everything to be perfect before taking action.',
      discoverMore: 'https://basalpay.com/',
      tags: ['QR Payment', 'Fintech'],
      industry: ['Web3', 'Payment'],
      image: '/assets/Mockup_BasalPay.png',
      alt: 'Basal Pay',
    }
  ]
};
